/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.thewalkingtec.CreationGUI.mobStructure.Builder;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabo
 */
public class gBuilder extends javax.swing.JFrame {

    /**
     * Creates new form gBuilder
     */
    public gBuilder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldsInMatrixTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rangeTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        unlockLevelTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        HPSTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gunTypeTextField = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        normalStateTextField = new javax.swing.JTextField();
        normalStateButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        attackStateTextField = new javax.swing.JTextField();
        attackStateButton = new javax.swing.JButton();
        createGunButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        healthTextField = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Crear arma");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Campos en la matriz:");

        jLabel4.setText("Rango:");

        jLabel5.setText("Nivel de desbloqueo:");

        jLabel6.setText("Golpes por segundo:");

        jLabel7.setText("Tipo de arma:");

        gunTypeTextField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "De contacto", "Medio alcance", "Aerea", "Impacto", "Ataque multiple" }));

        jLabel8.setText("Archivo de imagen (Estado normal):");

        normalStateButton.setText("...");
        normalStateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalStateButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Archivo de imagen (Ataque):");

        attackStateButton.setText("jButton2");
        attackStateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackStateButtonActionPerformed(evt);
            }
        });

        createGunButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        createGunButton.setText("Crear arma");
        createGunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGunButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Vida:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(gunTypeTextField, javax.swing.GroupLayout.Alignment.LEADING, 0, 153, Short.MAX_VALUE)
                                .addComponent(unlockLevelTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rangeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldsInMatrixTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel3))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(attackStateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(attackStateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(normalStateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(normalStateButton)))))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(healthTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(HPSTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                            .addComponent(jLabel10))
                        .addGap(75, 75, 75)
                        .addComponent(createGunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(normalStateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(normalStateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldsInMatrixTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attackStateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attackStateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rangeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unlockLevelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createGunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HPSTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(healthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gunTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createGunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGunButtonActionPerformed
        
        try {
        String name = nameTextField.getText();
        String normalStateFile = normalStateTextField.getText();
        String attackStateFile = attackStateTextField.getText();
        String type = (String) gunTypeTextField.getSelectedItem();
        String range = rangeTextField.getText();
        String unlockLevel = unlockLevelTextField.getText();
        String HPS = HPSTextField.getText();
        String fieldsInMatrix = fieldsInMatrixTextField.getText();
        String health = healthTextField.getText();
        
        String txtFilePath = "src/main/java/com/mycompany/thewalkingtec/CreationGUI/mobFiles/Guns/" + name + ".txt";
        
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(txtFilePath))) {
            // Escribir los datos en el archivo de texto, uno por línea
            writer.write(name);
            writer.newLine();
            writer.write(type);
            writer.newLine();
            writer.write(health);
            writer.newLine();
            writer.write(HPS);
            writer.newLine();
            writer.write(range);
            writer.newLine();
            writer.write(unlockLevel);
            writer.newLine();
            writer.write(fieldsInMatrix);
            writer.newLine();
            writer.write(normalStateFile);
            writer.newLine();
            writer.write(attackStateFile);
            
            JOptionPane.showMessageDialog(this, "Arma creado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        } catch (NumberFormatException e) {
        // Manejar excepciones si los valores no son números válidos
        e.printStackTrace();
        
        
    }//GEN-LAST:event_createGunButtonActionPerformed
    }
    private void normalStateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalStateButtonActionPerformed
        
        JFileChooser fc = new JFileChooser();
        
        int seleccion = fc.showOpenDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION){ //COMPROBAR QUE SE DE CLICK EN ACEPTAR
            File archivo = fc.getSelectedFile();
            normalStateTextField.setText(archivo.getAbsolutePath());
        }      
    }//GEN-LAST:event_normalStateButtonActionPerformed

    private void attackStateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackStateButtonActionPerformed
        
        JFileChooser fc = new JFileChooser();
        
        int seleccion = fc.showOpenDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION){ //COMPROBAR QUE SE DE CLICK EN ACEPTAR
            File archivo = fc.getSelectedFile();
            attackStateTextField.setText(archivo.getAbsolutePath());
        }
        
    }//GEN-LAST:event_attackStateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gBuilder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HPSTextField;
    private javax.swing.JButton attackStateButton;
    private javax.swing.JTextField attackStateTextField;
    private javax.swing.JButton createGunButton;
    private javax.swing.JTextField fieldsInMatrixTextField;
    private javax.swing.JComboBox<String> gunTypeTextField;
    private javax.swing.JTextField healthTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton normalStateButton;
    private javax.swing.JTextField normalStateTextField;
    private javax.swing.JTextField rangeTextField;
    private javax.swing.JTextField unlockLevelTextField;
    // End of variables declaration//GEN-END:variables
}