/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.thewalkingtec.CreationGUI.mobStructure.Builder;

import java.io.BufferedWriter;
import java.io.File;
import javax.swing.JFileChooser;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author Fabo
 */
public class zBuilder extends javax.swing.JFrame {

    /**
     * Creates new form zBuilder
     */
    public zBuilder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        zombieName = new javax.swing.JTextField();
        fieldsInMatrix = new javax.swing.JTextField();
        rangeTextField = new javax.swing.JTextField();
        unlockLevel = new javax.swing.JTextField();
        hps = new javax.swing.JTextField();
        zombieType = new javax.swing.JComboBox<>();
        createButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        normalStateTextField = new javax.swing.JTextField();
        normalStateButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        attackStateTextField = new javax.swing.JTextField();
        attackStateButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        healthTextField = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Crear zombie");

        zombieName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zombieNameActionPerformed(evt);
            }
        });

        fieldsInMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldsInMatrixActionPerformed(evt);
            }
        });

        zombieType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "De contacto", "Aereo", "De choque", "Medio alcance" }));

        createButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        createButton.setText("Crear zombie");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        createButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                createButtonKeyPressed(evt);
            }
        });

        jLabel2.setText("Archivo de imagen (Estado normal): ");

        normalStateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalStateTextFieldActionPerformed(evt);
            }
        });

        normalStateButton.setText("...");
        normalStateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                normalStateButtonMouseClicked(evt);
            }
        });
        normalStateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalStateButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Archivo de imagen (Ataque):");

        attackStateButton.setText("jButton1");
        attackStateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackStateButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre:");

        jLabel5.setText("Campos en la matriz:");

        jLabel6.setText("Rango:");

        jLabel7.setText("Nivel de aparicion:");

        jLabel9.setText("Golpes por segundo:");

        jLabel10.setText("Tipo de zombie:");

        jLabel8.setText("Vida:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zombieType, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(healthTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unlockLevel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zombieName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldsInMatrix, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rangeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hps, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(normalStateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(normalStateButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(attackStateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(attackStateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(normalStateButton)
                            .addComponent(normalStateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zombieName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(fieldsInMatrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(attackStateButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rangeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(attackStateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unlockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8))
                    .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(healthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zombieType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zombieNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zombieNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zombieNameActionPerformed

    private void createButtonKeyPressed(java.awt.event.KeyEvent evt) {                                        
        // TODO add your handling code here:
    }

    private void normalStateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalStateButtonActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fc = new JFileChooser();
        
        int seleccion = fc.showOpenDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION){ //COMPROBAR QUE SE DE CLICK EN ACEPTAR
            File archivo = fc.getSelectedFile();
            normalStateTextField.setText(archivo.getAbsolutePath());
        }         
    }//GEN-LAST:event_normalStateButtonActionPerformed

    private void normalStateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalStateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_normalStateTextFieldActionPerformed
     
    private void normalStateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_normalStateButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_normalStateButtonMouseClicked

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
       
        try {
        String name = zombieName.getText();
        String normalStateFile = normalStateTextField.getText();
        String attackStateFile = attackStateTextField.getText();
        String type = (String) zombieType.getSelectedItem();
        String range = rangeTextField.getText();
        String genericUnlocked = unlockLevel.getText();
        String genericSizeInMatrix = fieldsInMatrix.getText();
        String genericHPS = hps.getText();
        String health = healthTextField.getText();

        // Obtener la ruta del archivo de texto
        String txtFilePath = "src/main/java/com/mycompany/thewalkingtec/CreationGUI/mobFiles/Zombies/" + name + ".txt";

        // Crear un objeto BufferedWriter para escribir en el archivo de texto
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(txtFilePath))) {
            // Escribir los datos en el archivo de texto, uno por línea
            writer.write(name);
            writer.newLine();
            writer.write(type);
            writer.newLine();
            writer.write(health);
            writer.newLine();
            writer.write(genericHPS);
            writer.newLine();
            writer.write(range);
            writer.newLine();
            writer.write(genericUnlocked);
            writer.newLine();
            writer.write(genericSizeInMatrix);
            writer.newLine();
            writer.write(normalStateFile);
            writer.newLine();
            writer.write(attackStateFile);
        } catch (IOException e) {
            e.printStackTrace();
        }

    } catch (NumberFormatException e) {
        // Manejar excepciones si los valores no son números válidos
        e.printStackTrace();
    }
        
        
    }//GEN-LAST:event_createButtonActionPerformed

    private void attackStateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackStateButtonActionPerformed
        
        JFileChooser fc = new JFileChooser();
        
        int seleccion = fc.showOpenDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION){ //COMPROBAR QUE SE DE CLICK EN ACEPTAR
            File archivo = fc.getSelectedFile();
            attackStateTextField.setText(archivo.getAbsolutePath());
        }  
    }//GEN-LAST:event_attackStateButtonActionPerformed

    private void fieldsInMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldsInMatrixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldsInMatrixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(zBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(zBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(zBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(zBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new zBuilder().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attackStateButton;
    private javax.swing.JTextField attackStateTextField;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField fieldsInMatrix;
    private javax.swing.JTextField healthTextField;
    private javax.swing.JTextField hps;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton normalStateButton;
    private javax.swing.JTextField normalStateTextField;
    private javax.swing.JTextField rangeTextField;
    private javax.swing.JTextField unlockLevel;
    private javax.swing.JTextField zombieName;
    private javax.swing.JComboBox<String> zombieType;
    // End of variables declaration//GEN-END:variables
}
